# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da9837fa43a19a6ce9140a469b4469fd474ff0bd63c0027cc5a70850da1c2cbc8a326abb5ef8dafffc4f113fe7d957f961f729ea5d9ccc29243e6aa8e94605b0

test:
  secret_key_base: 821ae0e0384b1ffe3baac4234cfd31ae8b5cefcd6f5a2b82c3e7f28acdef4b4f98cb0cd907a7ebaec2485de83b5a3a88b53a31d7e867c29869d5c9be32dcf2b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
